### ISSUE TITLE
Publish Strips '+' Suffix From Version

### ISSUE THREAD

**Issue by davidtaylor-juul** [mpetuska/npm-publish#50]
Sometimes we use a re-publishing pattern where we append ` +1` to the version, e.g. `1.0.0+1`.

When executing the `publishJsPackageToGithubRegistry` task, it appears the `+1` suffix is stripped. Note that the `packJsPackage` works fine, it is the publish task only that seems to do this.

Note also that a suffix like `-1` works fine, it seems only `+` is a problem.

#### Plugin Config
```kotlin
npmPublish {
    organization.set("testingstuff")
    version.set("${project.version}")

    registries {
        github {
            access.set(RESTRICTED)
            dry.set(true)
        }
    }

    packages {
        val js by getting {
            packageName.set("a-test")
        }
    }
}
```

#### Github Action
```yaml
name: Publish
on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "adopt-hotspot"
          java-version: "11.0.11+9"

      - name: Publish Dump Info
        run: |
          env

      - name: PublishShowVer
        run: >
          echo
          "GITHUB_REF tag is: "
          -Pversion=${GITHUB_REF/refs\/tags\//}

      - name: Pack Npm
        run: >
          ./gradlew
          -Pversion="${GITHUB_REF/refs\/tags\//}"
          packJsPackage

      - name: Publish Npm
        run: >
          ./gradlew
          -Pversion="${GITHUB_REF/refs\/tags\//}"
          -Pnpm.publish.registry.github.authToken="test-token"
          publishJsPackageToGithubRegistry
```

#### Output For v1.0.3-1 ✅ 
```
GITHUB_REF tag is:  -Pversion=1.0.3-1

> Task :bridge: publishJsPackageToGithubRegistry
npm notice 📦  @testingstuff/a-test@1.0.3-1
```

#### Output For v1.0.2+1 ⛔ 
```
GITHUB_REF tag is:  -Pversion=1.0.2+1

> Task :bridge:publishJsPackageToGithubRegistry
npm notice 📦  @ testingstuff/a-test@1.0.2
```

_Note the `+1` suffix is missing on `1.0.2` ^^_
